import { Gauge } from "lucide-react";
import { HeroCard } from "../components/HeroCard";
import { MultiChart } from "../components/panels/MultiChart";
import { Heatmap } from "../components/panels/Heatmap";
import { CurveChart } from "../components/panels/CurveChart";
import { MoversPanel } from "../components/panels/MoversPanel";
import { NewsPanel } from "../components/panels/NewsPanel";
import { SentimentPanel } from "../components/panels/SentimentPanel";
import { EconCalendar } from "../components/panels/EconCalendar";
import { InventorySnap } from "../components/panels/InventorySnap";
import { ShippingPanel } from "../components/panels/ShippingPanel";
import { WeatherRisk } from "../components/panels/WeatherRisk";
import { Card } from "../components/primitives/Card";
import { SourceTag } from "../components/primitives/SourceTag";
import { AsOf } from "../components/primitives/AsOf";
import { HERO } from "../data/mock";
import { useLive } from "../lib/useLive";

const DIM_STATE_COLOR = {
  Tight: "text-sky-400", Oversupplied: "text-amber-400", Balanced: "text-zinc-300",
  Backwardation: "text-emerald-400", Contango: "text-sky-400", Flat: "text-zinc-300",
  Low: "text-emerald-400", Normal: "text-zinc-300", High: "text-amber-400",
  Up: "text-emerald-400", Down: "text-red-400", Range: "text-zinc-300",
  Heating: "text-orange-400", Driving: "text-emerald-400", Shoulder: "text-zinc-300",
};
const DIM_TITLE = { inventory: "Inv", structure: "Curve", volatility: "Vol", trend: "Trend", season: "Season" };

// Market briefing — one-line synthesis of regime + top signal + biggest mover,
// generated by the regime engine (server/compute/regime.js → buildNarrative).
const NarrativeHeader = () => {
  const { data, live, stale } = useLive("/api/narrative", { headline: "", drivers: [] }, useLive.REFRESH.slow);
  // Slim placeholder with the same footprint while the headline loads, so the
  // rest of the page doesn't jump when the briefing arrives.
  if (!data?.headline) {
    return (
      <Card padding={false} className="relative overflow-hidden bg-gradient-to-r from-amber-500/[0.04] via-transparent to-transparent">
        <div className="absolute left-0 top-0 bottom-0 w-[3px] bg-gradient-to-b from-amber-400/40 to-amber-600/40" />
        <div className="p-4 pl-5 flex items-start gap-3.5 animate-pulse">
          <div className="w-9 h-9 rounded-md bg-amber-500/10 border border-amber-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
            <Gauge size={18} className="text-amber-400/60" strokeWidth={1.75} />
          </div>
          <div className="flex-1 min-w-0">
            <span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-amber-400/60">Market Briefing</span>
            <div className="h-3.5 mt-2 rounded bg-[#1c1d22] w-3/4" />
            <div className="h-2.5 mt-2 rounded bg-[#15161a] w-1/3" />
          </div>
        </div>
      </Card>
    );
  }
  return (
    <Card padding={false} className="relative overflow-hidden bg-gradient-to-r from-amber-500/[0.05] via-transparent to-transparent">
      <div className="absolute left-0 top-0 bottom-0 w-[3px] bg-gradient-to-b from-amber-400 to-amber-600" />
      <div className="p-4 pl-5 flex items-start gap-3.5">
        <div className="w-9 h-9 rounded-md bg-amber-500/10 border border-amber-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
          <Gauge size={18} className="text-amber-400" strokeWidth={1.75} />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-amber-400/90">Market Briefing</span>
            <SourceTag live={live && !stale} stale={stale} source="regime"
              note="Auto-synthesized from the current regime, the top-ranked signal, and the biggest live mover." />
            {data.asOf && <span className="ml-auto"><AsOf date={data.asOf} prefix="regime" /></span>}
          </div>
          <p className="text-[13.5px] text-zinc-100 leading-relaxed mt-1.5 max-w-4xl">{data.headline}</p>
          <div className="flex flex-wrap gap-1.5 mt-2.5">
            {(data.drivers || []).map((d) => (
              <span key={d.dim} className="inline-flex items-center gap-1 text-[9px] font-mono px-1.5 py-0.5 bg-[#0a0b0e] border border-[#1c1d22] rounded" title={d.driver}>
                <span className="text-zinc-600 uppercase tracking-wider">{DIM_TITLE[d.dim] || d.dim}</span>
                <span className={DIM_STATE_COLOR[d.state] || "text-zinc-300"}>{d.state}</span>
              </span>
            ))}
          </div>
        </div>
      </div>
    </Card>
  );
};

export const PageDashboard = () => {
  // Live front-month quotes (Yahoo Finance); seeded HERO is the fallback.
  const { data: heroes } = useLive("/api/instruments", HERO);

  return (
    <div className="space-y-3">
      {/* Market briefing — regime-driven synthesis */}
      <NarrativeHeader />

      {/* Five instruments */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-px bg-[#1c1d22]">
        {heroes.map((d) => (
          <HeroCard key={d.sym} d={d} />
        ))}
      </div>

      {/* Main grid */}
      <div className="grid grid-cols-12 gap-3">
        <div className="col-span-12 lg:col-span-8 space-y-3">
          <MultiChart />
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <CurveChart />
            <Heatmap />
          </div>
          <MoversPanel />
        </div>

        {/* Right rail — on desktop the inner stack is absolutely filled to the
            (taller) LEFT column's height, so the news wire scrolls to fit rather
            than driving the row height (which would leave blank space on the
            left). On mobile it falls back to normal stacking. */}
        <div className="col-span-12 lg:col-span-4 lg:relative">
          <div className="flex flex-col gap-3 lg:absolute lg:inset-0">
            <NewsPanel compact fill />
            <SentimentPanel />
            <EconCalendar />
          </div>
        </div>
      </div>

      {/* Fundamentals snapshot */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        <InventorySnap />
        <ShippingPanel />
        <WeatherRisk />
      </div>
    </div>
  );
};
